### ISSUE TITLE
Images not being pulled with source set to Github

### ISSUE THREAD

**Issue by oakbrad** [Jafner/5etools-docker#12]
I've set SOURCE=GITHUB but I'm not getting any images downloaded. It successfully gets the 5etools web content (~200MB) and starts up Apache, but no media content.

Not seeing any errors in the logs

```
 === Checking directory permissions for /usr/local/apache2/htdocs
drwxr-xr-x 19 1000 1000 4096 Jan  8 20:51 /usr/local/apache2/htdocs
SOURCE=GITHUB
 === Using GitHub mirror at https://github.com/5etools-mirror-2/5etools-mirror-2.github.io.git
 === Using existing git repository
 === Pulling from GitHub with images... (This will take a while)
Your branch is up to date with 'origin/main'.
Already up to date.
 === Starting version 1.197.3
```

**Comment by Jafner** [comment]
Hmm. Good question. 

It looks like the new mirror-2 has no images for some reason. And it's already one version behind (1.197 vs 1.198).  

So now we have to choose between images and up-to-date code.

**Comment by Jafner** [comment]
I'll write up a fix so you can input your own choice of Git URL

**Comment by Jafner** [comment]
Should be good to go once that deploys to Dockerhub.
