### ISSUE TITLE
No images

### ISSUE THREAD

**Issue by Greg-Malski** [Jafner/5etools-docker#13]
Heads up, the new "mirror-2" has "images" in separate repo from everything else, so even though someone might think they are pulling the version with images, no images are received.

**Comment by Jafner** [comment]
I was wondering where they put the images for versions later than 1.197.4...

**Comment by Jafner** [comment]
At least the images repo is a complete repo, and not *just* the images.

**Comment by Jafner** [comment]
> At least the images repo is a complete repo, and not _just_ the images.

Wrong. It's literally just the image files. Ugh. I guess I'll have to pull the second repo as a module??

**Comment by Jafner** [comment]
Spin down the container (`docker-compose down`), burn the old data (`sudo rm -rf ~/5etools-docker/`), and then spin up again like new (`docker-compose up -d && docker-compose logs -f`)

Working for me. Feel free to reopen if you continue to have issues.
