### ISSUE TITLE
CORS for Foundry

### ISSUE THREAD

**Issue by kurisu-n** [Jafner/5etools-docker#15]
Hey. I'm trying to use this mirror in my self-hosted foundry, but I get "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at {my url} (Reason: CORS request did not succeed). Status code: (null).".

How would I go about enabling CORS for this image?

**Comment by Jafner** [comment]
That's outside the scope of what I wanna support for this image, but I think I can point you in the right direction.  

This StackEx might help: https://stackoverflow.com/questions/45363822/how-to-enable-cors-for-docker-apache-httpd-server  

My image is based on [httpd](https://hub.docker.com/_/httpd), so the commands they describe should work similarly.  

Something like:  

```sh
docker exec 5etools-docker bash -c 'printf "<Directory \"/var/www/html\">\n        Header set Access-Control-Allow-Origin \"*\"\n</Directory>\n" >> /usr/local/apache2/conf/extra/cors.conf'
docker exec 5etools-docker bash -c 'apachectl -k restart'
```

I'm gonna close this issue, but let me know if that works for you.
