### ISSUE TITLE
Bug: No local version detected. Exiting.

### ISSUE THREAD

**Issue by LordVoldeBean** [Jafner/5etools-docker#4]
Unable to stand up the container with a local version of 5etools after downloading the website via:
```
mkdir -p ~/5etools-docker/htdocs && cd ~/5etools-docker
curl -o docker-compose.yml https://raw.githubusercontent.com/Jafner/5etools-docker/main/docker-compose.yml
docker-compose up -d && docker logs -f 5etools-docker

```
then standing down container with 
```
sudo docker-compose stop
```

then setting `AUTOUPDATE=false` in dockerfile.

and running 

```
sudo docker-compose up -d && docker logs -f 5etools-docker
Starting 5etools-docker ... done
Auto update disabled. Checking for local version...
 === No local version detected. Exiting.
Auto update disabled. Checking for local version...
 === No local version detected. Exiting.
Auto update disabled. Checking for local version...
 === No local version detected. Exiting.

```

**Comment by Jafner** [comment]
This issue occurs because the script does not write an `htdocs/version` file after updating. Will be fixing this shortly with a workaround. In the longer term, I'll add version parsing from the index.html file itself.

**Comment by Jafner** [comment]
We now parse the version after the github clone with 14b7fa1
