### ISSUE TITLE
Script doesn't pull files, returns errors

### ISSUE THREAD

**Issue by TheCheshireMan** [Jafner/5etools-docker#5]
Hi,

I've been trying to use this script to setup a local 5etools instance, but I haven't had any luck getting it to work. Every configuration I've run seems to have some kind of trouble downloading the files.

Leaving every environment variable default returns this:

>5etools-docker    | Auto update enabled. Checking for remote version...
>5etools-docker    |  === Checking connection to https://github.com/5etools-mirror-1/5etools-mirror-1.github.io.git...
>5etools-docker    |  === Using GitHub structure to update from https://github.com/5etools-mirror-1/5etools-mirror-1.github.io.git
>5etools-docker    |  === Warning: images will be downloaded automatically, which will take longer
>5etools-docker    |  === Pulling from GitHub... (This might take a while)
>5etools-docker    | jq: error: Could not open file package.json: No such file or directory
>5etools-docker    |  === Starting version
>5etools-docker    | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.26.0.2. Set the >'ServerName' directive globally to suppress this message
>5etools-docker    | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.26.0.2. Set the >'ServerName' directive globally to suppress this message
>5etools-docker    | [Mon Apr 25 08:20:33.690232 2022] [mpm_event:notice] [pid 16:tid 548358406160] AH00489: Apache/2.4.52 >(Unix) configured -- resuming normal operations
>5etools-docker    | [Mon Apr 25 08:20:33.691889 2022] [core:notice] [pid 16:tid 548358406160] AH00094: Command line: 'httpd -D >FOREGROUND'

Attempting to use the 'get' DL-method (setting "https://get.5e.tools/", with or without trailing slash, as link) returns this:

>5etools-docker    | Auto update enabled. Checking for remote version...
>5etools-docker    |  === Checking connection to https://get.5e.tools/...
>5etools-docker    |  === Could not connect to https://get.5e.tools/
>5etools-docker    |  === No local version found! You must be able to access https://get.5e.tools/ to grab the 5eTools files.
>5etools-docker    |  === Hint: Make sure you have the correct DL_TYPE environment variable set.
>5etools-docker exited with code 1

With the same method, using "get.5e.tools" as link returns this:

>5etools-docker    | Auto update enabled. Checking for remote version...
>5etools-docker    |  === Checking connection to get.5e.tools...
>5etools-docker    |  === Using get structure to download from get.5e.tools
>5etools-docker    |  === WARNING: This part of the script has not yet been tested. Please open an issue on the github if you have >trouble.
>5etools-docker    |  === Local version () outdated, updating to .zip ...
>5etools-docker    |  === Downloading new remote version...
>5etools-docker    | Warning: Remote filename has no length!
>5etools-docker    |
>5etools-docker    |  === Extracting site...
>5etools-docker    |
>5etools-docker    | 7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
>5etools-docker    | p7zip Version 16.02 (locale=C,Utf16=off,HugeFiles=on,64 bits,4 CPUs LE)
>5etools-docker    |
>5etools-docker    | Scanning the drive for archives:
>5etools-docker    |
>5etools-docker    |
>5etools-docker    | Command Line Error:
>5etools-docker    | Cannot find archive
>5etools-docker    |  === Configuring...
>5etools-docker    | sed: can't read index.html: No such file or directory
>5etools-docker    | sed: can't read index.html: No such file or directory
>5etools-docker    | sed: can't read 5etools.html: No such file or directory
>5etools-docker    |  === Cleaning up downloads
>5etools-docker    |  === Done!
>5etools-docker    | jq: error: Could not open file package.json: No such file or directory
>5etools-docker    |  === Starting version
>5etools-docker    | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.26.0.2. Set the >'ServerName' directive globally to suppress this message
>5etools-docker    | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.26.0.2. Set the 'ServerName' directive globally to suppress this message
>5etools-docker    | [Mon Apr 25 08:32:06.219071 2022] [mpm_event:notice] [pid 30:tid 548412321808] AH00489: Apache/2.4.52 >(Unix) configured -- resuming normal operations
>5etools-docker    | [Mon Apr 25 08:32:06.220635 2022] [core:notice] [pid 30:tid 548412321808] AH00094: Command line: 'httpd -D >FOREGROUND'

Any idea what I'm doing wrong? Thanks for your time.

**Comment by Wildcarde** [comment]
Digging through the script it seems the stated defaults in the compose file are not honored. If you sent it explicitly for each of the 4 env vars and then download fresh it should work. Takes a bit with everything enabled (i believe it took about 10 minutes to get to a coherent fully checked out state).

**Comment by Jafner** [comment]
Sorry I've been inactive on this.  

1. `https://get.5e.tools` has been down for a while. I'll make a note in the Readme about it. Hopefully it comes back up. It was really nice.  
2. I'm digging into the variables issue. Will get it resolved soon. 
3. I'm also going to rename the misleading "autoupdate" variable. Gonna call it "update_on_start" or something like that.

**Comment by Jafner** [comment]
@TheCheshireMan For your first case, I'm not sure why your instance failed to pull from the Github. The only error that pops up is `jq` failing to find package.json. Not sure why that would be the case. It looks like it launched apache (`httpd`), but it sounds like it was probably a dead page, yeah?

I'm going to refactor "IMG", "DL_TYPE", and "DL_LINK" to just "SOURCE" and hardcode the links.  
This script was written when we were unsure about where the 5eTools source would be hosted, so I wanted to afford flexibility if you needed to pull from an alternate git repo.  

Anyway, it's been down for a while. We're going to assume the Github mirror is the default for the foreseeable future. But I'll keep support for the get.5e.tools method for now. I'm going to drop support for Mega, as there is no actively maintained Mega source. If you use Mega, you can just manually place the files in htdocs and use OFFLINE_MODE. 

Working on an update now with the following:

- Simplified compose file (IMG & DL_TYPE & DL_LINK --> SOURCE).
- Rename "AUTOUPDATE" to the more sensible "OFFLINE_MODE", which just runs the server with existing files.
- Refactored script to accommodate the above (and make some other improvements).
- Move defaults from script to Compose.  
- Make error handling a little clearer around variables.

**Comment by Jafner** [comment]
@TheCheshireMan Interesting.  

I was able to reproduce the error you saw in your first case by removing the volume mapping from my Docker-compose file or using a Docker-managed volume. Can you share the contents of your `docker-compose.yml`?  

I'm not entirely sure why, but it seems a host volume mapping is required.

**Comment by Jafner** [comment]
I've pushed the changes to the latest image. Because the new image changes the way the git repository is configure, you will need to wipe the volume and re-run the image.

**Comment by Jafner** [comment]
Should be resolved now.  

Next update will work on homebrew support.

**Comment by Jafner** [comment]
Note that you will need to pull the latest version to get support for GITHUB-NOIMG.
