### ISSUE TITLE
Home page no loading error 404

### ISSUE THREAD

**Issue by lvl5-Mage** [Jafner/5etools-docker#9]
The home page does not load.  Every other page loads and works just fine.
Chrome console shows: Failed to load resource: the server responded with a status of 404 (Not Found)
![1Capture](https://github.com/Jafner/5etools-docker/assets/110032300/b994a43c-5e5b-420a-82dc-7113667ea13a)
![2Capture](https://github.com/Jafner/5etools-docker/assets/110032300/d156efd7-38e1-448a-8b0c-0e7b9b03b0aa)

**Comment by Jafner** [comment]
@lvl5-Mage Are you able to reproduce this issue with the latest version of the image?

**Comment by Jafner** [comment]
I believe the name of the homepage file was changed at some point, which led to this behavior on my instance. 

My best recommendation is to wipe and re-pull the directory.

**Comment by Jafner** [comment]
Closing as stale. Feel free to re-open if you can reproduce after a repo wipe and pulling the latest version of the image.
